### ISSUE TITLE
lazy loading mathjax.js

### ISSUE THREAD

**Issue by Chenyao2333** [boolesrings/Simple-Mathjax-wordpress-plugin#15]
I so appreciate this plugin, it saves me in annoying configuration.

But it a little bugs me. If the network is congested, the whole page will be blocked until mathjax.js loaded or failed. So please lazy load the mathjax.js.

**Comment by scoskey** [comment]
Gotcha, thank you! I never thought about it because it hasn't lagged for me personally.

**Comment by scoskey** [comment]
Two options:
(1) use some hack to add async to the script tag https://matthewhorne.me/defer-async-wordpress-scripts/
(2) add mathjax to the footer instead. https://developer.wordpress.org/reference/functions/wp_enqueue_script/

**Comment by pkra** [comment]
Both are fine I think (and (2) seems more robust). 

FWIW, MathJax v2 loads ~19k gzip'ed synchronously, everything else is loaded asynchronously no matter the setup.
