### ISSUE TITLE
PHP warning messages when updating

### ISSUE THREAD

**Issue by kebekus** [boolesrings/Simple-Mathjax-wordpress-plugin#25]
Thank you for this wonderful plugin.

A while ago I started to see error messages whenever I try to check for updates. More precisely, the command 'wp plugin update --all' returns the following:

PHP Warning:  array_merge(): Argument #1 is not an array in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 29
Warning: array_merge(): Argument #1 is not an array in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 29
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
PHP Warning:  array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Warning: array_key_exists() expects parameter 2 to be array, null given in /var/www/html/wp-content/plugins/simple-mathjax/simple-mathjax.php on line 46
Success: Plugin already updated.

**Comment by pkra** [comment]
Thanks for the report.

@christianp do you have time to take a look?

**Comment by christianp** [comment]
I've rearranged the code so that everything is under a `SimpleMathJax` namespace. Can you pull the latest version from GitHub and let me know if that's any better?

**Comment by kebekus** [comment]
Hi, thanks for your **very quick** response. I puller version 2a5aa9e from GitHub a few minutes ago, and
* The plugin still works
* The issue is gone.
Thanks again!

**Comment by christianp** [comment]
Fab! You caught me at the right time.

**Comment by pkra** [comment]
Thanks @christianp!

**Comment by toddpfaff** [comment]
I need this fix as well.  Is it expected that I am not getting this in the most up-to-date version of the simple-mathjax plugin found via wp-cli?  wp-cli is telling me that I have version 2.0 and no update is available.  Do I have to pull it via git for the time being?

**Comment by pkra** [comment]
Hm. Looks indeed that the plugin registry is still at 2.0.

ping @christianp @scoskey do you happen to have access to the Wordpress SVN to push a release? I'm unable to get on at the moment.

**Comment by christianp** [comment]
I had changed the `Stable tag` field in readme.txt as the [wordpress docs](https://wordpress.org/plugins/developers/#readme) said, but it seems that I actually needed to change the `Version` line in simple-mathjax.php.

The wordpress.org plugin page now says that the current version is 2.0.1, so hopefully that has sorted it. @toddpfaff can you tell me if you get the right version now?

**Comment by toddpfaff** [comment]
I'm not seeing a change yet in wp-cli output.  Maybe we have to wait a 
while?

+------------------------------+----------+-----------+---------+
| name                         | status   | update    | version |
+------------------------------+----------+-----------+---------+
| akismet                      | active   | none      | 4.1.6   |
| clean-my-archives            | inactive | none      | 1.2.0   |
| jquery-collapse-o-matic      | active   | none      | 1.7.13  |
| enable-oembed-discovery      | active   | none      | 1.0.0   |
| gutenberg                    | inactive | available | 8.8.0   |
| jetpack                      | active   | none      | 8.9     |
| pods                         | active   | none      | 2.7.22  |
| recent-posts-widget-extended | active   | none      | 0.9.9.7 |
| simple-mathjax               | active   | none      | 2.0     |
| simple-yearly-archive        | active   | none      | 2.1.2   |
| user-role-editor             | active   | none      | 4.56    |
| wordpress-importer           | inactive | none      | 0.7     |
+------------------------------+----------+-----------+---------+

**Comment by pkra** [comment]
@toddpaff let us know if the problem persists.

**Comment by toddpfaff** [comment]
Problem resolved!

wp-cli --path=. plugin list
+------------------------------+----------+-----------+---------+
| name                         | status   | update    | version |
+------------------------------+----------+-----------+---------+
| simple-mathjax               | active   | none      | 2.0.1   |
+------------------------------+----------+-----------+---------+

Thanks!

**Comment by pkra** [comment]
Thanks for following up with us.
