### ISSUE TITLE
Renders of equations cutoff in PC and Mobile Platforms

### ISSUE THREAD

**Issue by 098tarik** [boolesrings/Simple-Mathjax-wordpress-plugin#26]
Hi! So we are currently using this plugin for our educational platform and there are currently issues where the math rendering cuts off at certain zoom distances. It seems almost random so it is hard to pin down the source of the problem. Below are examples: 

![Image from iOS](https://user-images.githubusercontent.com/23299810/77800720-cea60180-704d-11ea-8bf9-c6860d888f3c.png)

![Image from iOS](https://user-images.githubusercontent.com/23299810/77800738-dbc2f080-704d-11ea-8d67-f1407e19d4ec.jpg)

**Comment by scoskey** [comment]
I have exactly the same issue myself, outside of Wordpress. I think it is a mathjax issue.  I am using Safari.

**Comment by 098tarik** [comment]
After contacting MathJax support, they say the issue could be with trying to render the content using CHTML instead of SVG. They suggested switching over to SVG

**Comment by scoskey** [comment]
Well maybe it'll be a workaround, but it's still an issue!

**Comment by 098tarik** [comment]
Well, would I be able to edit the plugin myself to find out? It is a bit urgent that we have this fixed

**Comment by scoskey** [comment]
Ah, I missed that you needed to know how. I think you can change to SVG output just using the plugin's configuration page. Change the custom MathJax cdn for V3 to "https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-svg.js" (assuming version 3... see the [MathJax docs](https://www.mathjax.org/#gettingstarted) for other options.)

**Comment by 098tarik** [comment]
That worked and the problem is fixed. Thank you!
