### ISSUE TITLE
math dont display correctly

### ISSUE THREAD

**Issue by thangisme** [boolesrings/Simple-Mathjax-wordpress-plugin#34]
I have the following input:
```
$\left\{ {\begin{array}{*{20}{c}} {{x_1},{x_2} \in K}\\ {{x_1} < {x_2}} \end{array}} \right. \Rightarrow f({x_1}) < f({x_2})$
```
It should output the following:
```math
\left\{ {\begin{array}{*{20}{c}} {{x_1},{x_2} \in K}\\ {{x_1} < {x_2}} \end{array}} \right. \Rightarrow f({x_1}) < f({x_2})
```
But in my website, the plugin display the following: 
![image](https://github.com/boolesrings/Simple-Mathjax-wordpress-plugin/assets/35835961/82814982-2fd7-4c2f-a7f8-b858d998ec97)
What have I done wrong?

**Comment by scoskey** [comment]
Is it live on the internet somewhere? We could try to look at it in action...

**Comment by pkra** [comment]
Wordpress is stripping a backslash.

`\left\{ `

in your input comes out as

`\left{ ` in the HTML.

The result is invalid TeX (and MathJax behaves somewhat similarly to "real" TeX, rendering the rest).

I don't think there's anythen we can do about wordpress doing unexpected unescaping like this.

**Comment by pkra** [comment]
Closing but happy to re-open.

**Comment by scoskey** [comment]
I suppose you could try using \\{ and see if it becomes \{

**Comment by christianp** [comment]
I think that this might have come about because WordPress strips out backslashes when you paste plain text in. I wrote `\{ x \}` in a textarea element on another page, then pasted it into the WP post editor. It appeared as `{ x }`.
I wonder if we can do anything to prevent this if it happens between LaTeX delimiters.
