### ISSUE TITLE
Symbol $ breaks the PHP variables

### ISSUE THREAD

**Issue by hoangthangta** [boolesrings/Simple-Mathjax-wordpress-plugin#35]
My website contains a series of articles about PHP programming so this package breaks the PHP variables such as $a. Is it possible to add a feature that can change the symbol $ by any special character?

**Comment by pkra** [comment]
It's already possible.

The link in the readme is unfortunately outdated and broken but https://docs.mathjax.org/en/latest/web/start.html#configuring-mathjax or https://docs.mathjax.org/en/latest/input/tex/delimiters.html are good starting points for learning how to configure MathJax delimiters.
